import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Badge from '../../components/common/Badge'; import Button from '../../components/common/Button'; import Card from '../../components/common/Card'; import Input from '../../components/common/Input'; import Modal from '../../components/common/Modal'; import Select from '../../components/common/Select';
import { useAuthStore } from '../../store/authStore';
import { createBooking, createTutorProfile, fetchBookings, fetchTutors, updateBooking, type Tutor } from './api';
export default function TutoringHub() {
 const qc = useQueryClient(); const { user } = useAuthStore(); const { data: tutors = [] } = useQuery({ queryKey: ['tutors'], queryFn: fetchTutors }); const { data: bookings = [] } = useQuery({ queryKey: ['bookings'], queryFn: fetchBookings });
 const [search, setSearch] = useState(''); const [department, setDepartment] = useState(''); const [selected, setSelected] = useState<Tutor | null>(null); const [subject, setSubject] = useState(''); const [scheduledAt, setScheduledAt] = useState(''); const [error, setError] = useState<string>(); const [isTutorModalOpen, setTutorModalOpen] = useState(false); const [tutorSubjects, setTutorSubjects] = useState(''); const [rate, setRate] = useState(''); const [availability, setAvailability] = useState(''); const [qualifications, setQualifications] = useState(''); const [tutorError, setTutorError] = useState<string>();
 const filtered = useMemo(() => tutors.filter((t) => (!department || t.department === department) && `${t.name} ${t.department} ${t.subjects.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [tutors, department, search]);
 const book = useMutation({ mutationFn: createBooking, onSuccess: () => { qc.invalidateQueries({ queryKey: ['bookings'] }); setSelected(null); }, onError: () => setError('Could not submit the booking request.') });
 const change = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'accepted' | 'declined' }) => updateBooking(id, status), onSuccess: () => qc.invalidateQueries({ queryKey: ['bookings'] }) });
 const publishTutor = useMutation({ mutationFn: () => createTutorProfile({ subjects: tutorSubjects.split(',').map((item) => item.trim()).filter(Boolean), hourlyRate: Number(rate), availability: availability.trim(), bio: qualifications.trim() }, user!), onSuccess: () => { qc.invalidateQueries({ queryKey: ['tutors'] }); setTutorModalOpen(false); }, onError: () => setTutorError('Could not publish your tutor profile.') });
 const open = (tutor: Tutor) => { setSelected(tutor); setSubject(tutor.subjects[0]); setScheduledAt(''); setError(undefined); };
 const myTutor = tutors.find((tutor) => tutor.userId === user?.id);
 return <><div className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Tutoring</h1><p className="mt-1 text-text-muted">Book help from verified Addis Ababa University students.</p></div><Button variant={myTutor ? 'outline' : 'primary'} onClick={() => { setTutorSubjects(myTutor?.subjects.join(', ') ?? ''); setRate(myTutor ? String(myTutor.hourlyRate) : ''); setAvailability(myTutor?.availability ?? ''); setQualifications(myTutor?.bio ?? ''); setTutorError(undefined); setTutorModalOpen(true); }}>{myTutor ? 'Edit my tutor profile' : 'Become a tutor'}</Button></div>
 <Card className="flex flex-col gap-3 sm:flex-row"><Input aria-label="Search tutors" placeholder="Search subject, tutor, or department" value={search} onChange={(e) => setSearch(e.target.value)} /><Select aria-label="Filter by department" value={department} onChange={(e) => setDepartment(e.target.value)} placeholder="All departments" options={[...new Set(tutors.map((t) => t.department))].map((value) => ({ value, label: value }))} /></Card>
 <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((tutor) => <Card key={tutor.id} className={`flex flex-col ${tutor.userId === user?.id ? 'ring-2 ring-primary-300' : ''}`} hoverable>{tutor.userId === user?.id && <Badge variant="primary" className="mb-3 self-start">My tutor profile</Badge>}<div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-100 font-semibold text-primary-700">{tutor.avatar}</div><div><h2 className="font-semibold">{tutor.name}</h2><p className="text-sm text-text-muted">{tutor.department}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{tutor.subjects.map((item) => <Badge key={item}>{item}</Badge>)}</div>{tutor.bio && <p className="mt-3 text-sm text-text-muted">{tutor.bio}</p>}<p className="mt-4 text-sm text-text-muted">Available: {tutor.availability}</p><div className="mt-5 flex items-center justify-between"><strong>ETB {tutor.hourlyRate}/hr</strong>{tutor.userId !== user?.id && <Button size="sm" onClick={() => open(tutor)}>Book session</Button>}</div></Card>)}</div>
 <section><h2 className="mb-3 text-xl font-semibold">My bookings</h2><Card padding="none"><div className="divide-y divide-border">{bookings.map((booking) => <div key={booking.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{booking.subject} with {booking.tutorName}</p><p className="text-sm text-text-muted">{new Date(booking.scheduledAt).toLocaleString()}</p></div><div className="flex items-center gap-2"><Badge variant={booking.status === 'accepted' ? 'success' : booking.status === 'declined' ? 'danger' : 'warning'}>{booking.status}</Badge>{booking.direction === 'received' && booking.status === 'pending' && <><Button size="sm" onClick={() => change.mutate({ id: booking.id, status: 'accepted' })}>Accept</Button><Button size="sm" variant="outline" onClick={() => change.mutate({ id: booking.id, status: 'declined' })}>Decline</Button></>}</div></div>)}</div></Card></section>
 <Modal isOpen={!!selected} onClose={() => setSelected(null)} title={`Book ${selected?.name ?? ''}`} footer={<><Button variant="outline" onClick={() => setSelected(null)}>Cancel</Button><Button isLoading={book.isPending} onClick={() => { if (!subject || !scheduledAt) return setError('Choose a subject and date/time.'); if (selected) book.mutate({ tutorId: selected.id, subject, scheduledAt }); }}>Send request</Button></>}><div className="space-y-4">{error && <p className="text-sm text-danger-600">{error}</p>}<Select label="Subject" value={subject} onChange={(e) => setSubject(e.target.value)} options={(selected?.subjects ?? []).map((value) => ({ value, label: value }))} /><Input label="Date and time" type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></div></Modal></div>
 <Modal isOpen={isTutorModalOpen} onClose={() => setTutorModalOpen(false)} title="Create tutor profile" footer={<><Button variant="outline" onClick={() => setTutorModalOpen(false)}>Cancel</Button><Button isLoading={publishTutor.isPending} onClick={() => { if (!tutorSubjects.split(',').some((item) => item.trim()) || !Number(rate) || !availability.trim() || !qualifications.trim()) return setTutorError('Add at least one subject, rate, availability, and qualifications.'); publishTutor.mutate(); }}>Publish profile</Button></>}><div className="space-y-4">{tutorError && <p className="rounded-lg bg-danger-50 p-3 text-sm text-danger-600">{tutorError}</p>}<Input label="Subjects taught" placeholder="Calculus, Python, Statistics" value={tutorSubjects} onChange={(e) => setTutorSubjects(e.target.value)} hint="Separate subjects with commas." required /><Input label="Hourly rate (ETB)" type="number" min="1" value={rate} onChange={(e) => setRate(e.target.value)} required /><Input label="Availability" placeholder="Weekdays after 5:00 PM" value={availability} onChange={(e) => setAvailability(e.target.value)} required /><div><label className="mb-1.5 block text-sm font-medium">Bio / qualifications</label><textarea value={qualifications} onChange={(e) => setQualifications(e.target.value)} rows={4} className="block w-full rounded-lg border border-border px-3 py-2 text-sm" placeholder="Your teaching experience and strengths" /></div></div></Modal></>;
}
